name: Linux CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: microsoft/playwright-github-action@v1
    - name: perl -V
      run: perl -V
    - name: Install dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install build-essential cpanminus
        sudo cpanm -n --installdeps .
    - name: Run tests
      run: |
        npm install
        npm test
      env:
        PERL5LIB: ${{ github.workspace }}/local/lib/perl5
        HARNESS_OPTIONS: j3